/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Product.form1;


import Check.Check_Email;
import Model.Model_ThietLap;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Repository.Repository_ThietLap;

/**
 *
 * @author ADMIN
 */
public class Form_ThietLap extends javax.swing.JPanel {
    private Repository_ThietLap rp = new Repository_ThietLap();
    private DefaultTableModel mol = new DefaultTableModel();
    private int i = -1;  

    /**
     * Creates new form Form_ThietLap
     */
    public Form_ThietLap() {
        initComponents();
        this.fillTable(rp.getAll());
    }

    void fillTable(ArrayList<Model.Model_ThietLap> list) {
        mol = (DefaultTableModel) tbl_taiKhoan.getModel();
        mol.setRowCount(0);
        for (Model_ThietLap x : list) {
            mol.addRow(x.toDataRow());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_maNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        rdo_quanLy = new javax.swing.JRadioButton();
        rdo_nhanVien = new javax.swing.JRadioButton();
        rdo_hoatDong = new javax.swing.JRadioButton();
        rdo_ngungHoatDong = new javax.swing.JRadioButton();
        txt_matKhau = new javax.swing.JPasswordField();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_timKiem = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        txt_hoTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tenDangNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_taiKhoan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Quản Lý Tài Khoản");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Mã NV:");

        txt_ID.setEnabled(false);

        txt_maNV.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tên đăng nhập:");

        btn_them.setBackground(new java.awt.Color(102, 102, 255));
        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_them.setForeground(new java.awt.Color(255, 255, 255));
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N
        btn_them.setText("THÊM");
        buttonGroup3.add(btn_them);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Mật khẩu:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Phân quyền:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tình trạng:");

        buttonGroup1.add(rdo_quanLy);
        rdo_quanLy.setText("Quản Lý");

        buttonGroup1.add(rdo_nhanVien);
        rdo_nhanVien.setText("Nhân Viên");

        buttonGroup2.add(rdo_hoatDong);
        rdo_hoatDong.setText("Hoạt Động");

        buttonGroup2.add(rdo_ngungHoatDong);
        rdo_ngungHoatDong.setText("Ngừng HĐ");

        txt_matKhau.setText("jPasswordField1");

        btn_xoa.setBackground(new java.awt.Color(102, 102, 255));
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/DELETE.png"))); // NOI18N
        btn_xoa.setText("XÓA");
        buttonGroup3.add(btn_xoa);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setBackground(new java.awt.Color(102, 102, 255));
        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/SAVE.png"))); // NOI18N
        btn_sua.setText("Sửa");
        buttonGroup3.add(btn_sua);
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_timKiem.setBackground(new java.awt.Color(102, 102, 255));
        btn_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_timKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_timKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Timkiem.png"))); // NOI18N
        btn_timKiem.setText("TÌM KIẾM");
        buttonGroup3.add(btn_timKiem);
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        btn_lamMoi.setBackground(new java.awt.Color(102, 102, 255));
        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_lamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_lamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/RESET.png"))); // NOI18N
        btn_lamMoi.setText("LÀM MỚI");
        buttonGroup3.add(btn_lamMoi);
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        txt_hoTen.setEnabled(false);
        txt_hoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hoTenActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Họ Tên:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tenDangNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(txt_maNV)
                                            .addComponent(txt_hoTen)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(61, 61, 61)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(rdo_quanLy)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo_nhanVien))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(rdo_hoatDong)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdo_ngungHoatDong))
                                    .addComponent(txt_matKhau))
                                .addGap(10, 73, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(btn_timKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_lamMoi)
                                .addGap(79, 79, 79))))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(rdo_quanLy)
                    .addComponent(rdo_nhanVien))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(rdo_hoatDong)
                            .addComponent(rdo_ngungHoatDong)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_tenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tbl_taiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã NV", "Họ Tên", "Tên Đăng Nhập", "Mật Khẩu", "Phân Quyền", "Trạng Thái"
            }
        ));
        tbl_taiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_taiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_taiKhoan);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("Danh sách tài khoản");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("Thông tin tài khoản");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(jLabel1)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
    if(this.readForm()!=null) {
       int chon=JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm k?");
       if(chon==0){
           rp.addThietLap(this.readForm());
           JOptionPane.showMessageDialog(this,"Thêm thành công");
           this.fillTable(rp.getAll());
       }
       else {
            JOptionPane.showMessageDialog(this,"Bạn chọn k thêm mới");
       }
    } 
    
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
     i=tbl_taiKhoan.getSelectedRow();
      if(i<0){
          JOptionPane.showMessageDialog(this, "Bạn chưa chọn dòng cần xóa");
      }
      else{
          int chon=JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn xóa ?");
          if(chon==0){
              int id=Integer.parseInt(tbl_taiKhoan.getValueAt(i, 0).toString());
              rp.deleteThietLap(id);
              JOptionPane.showMessageDialog(this, "Xóa thành công");
              this.fillTable(rp.getAll());
          }
          else{
              JOptionPane.showMessageDialog(this, "Bạn không chọn xóa");
          }
      }

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
                i=tbl_taiKhoan.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn");
        }
        else{
            if(this.readForm1()!=null){
                int chon=JOptionPane.showConfirmDialog(this, "Bạn chắc chắn sửa?");
                if(chon==0){
                    int id=Integer.parseInt(tbl_taiKhoan.getValueAt(i, 0).toString());
                    rp.updateThietLap(id, this.readForm1());
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    this.fillTable(rp.getAll());
                }
            }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        // TODO add your handling code here:
        String tenCanTim=JOptionPane.showInputDialog(this,"Mời nhập tên đăng nhập");
         if(rp.TimTen(tenCanTim).isEmpty()){
             JOptionPane.showMessageDialog(this,"Không tìm thấy");
         }
         else{
             JOptionPane.showMessageDialog(this,"Có tìm được");
             this.fillTable(rp.TimTen(tenCanTim));
         }

    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
        txt_ID.setText(null);
        txt_maNV.setText(null);
        txt_hoTen.setText(null);
        txt_tenDangNhap.setText(null);
        txt_matKhau.setText(null);   
        rdo_nhanVien.setSelected(true);
        rdo_ngungHoatDong.setSelected(true);

    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void tbl_taiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_taiKhoanMouseClicked
        // TODO add your handling code here:
        i = tbl_taiKhoan.getSelectedRow();
        this.showData(i);

    }//GEN-LAST:event_tbl_taiKhoanMouseClicked

    private void txt_hoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hoTenActionPerformed

        void showData(int index) {       
        String id;
        String maNV;
        String tenNV;
        String tenDangNhap;
        String matKhau;
        String phanQuyen;
        String tinhTrang;
        id = tbl_taiKhoan.getValueAt(index, 0).toString();
        maNV = tbl_taiKhoan.getValueAt(index, 1).toString();
        tenNV = tbl_taiKhoan.getValueAt(index, 2).toString();
        tenDangNhap = tbl_taiKhoan.getValueAt(index, 3).toString();
        matKhau = tbl_taiKhoan.getValueAt(index, 4).toString();
        phanQuyen = tbl_taiKhoan.getValueAt(index, 5).toString();
        tinhTrang = tbl_taiKhoan.getValueAt(index, 6).toString();
        txt_ID.setText(id);
        txt_maNV.setText(maNV);
        txt_hoTen.setText(tenNV);
        txt_tenDangNhap.setText(tenDangNhap);
        txt_matKhau.setText(matKhau);
        
        if (phanQuyen.equalsIgnoreCase("QL")) {
            rdo_quanLy.setSelected(true);
        } else {
            rdo_nhanVien.setSelected(true);
        }
        if (tinhTrang.equalsIgnoreCase("HĐ")) {
            rdo_hoatDong.setSelected(true);
        } else {
            rdo_ngungHoatDong.setSelected(true);
        }
    }

    Model_ThietLap readForm(){
    String maNV;
    String tenNV;
    String tenDangNhap;
    String matKhau;
    boolean phanQuyen;
    boolean trangThai;
    String thongbao="";
    
    maNV=txt_maNV.getText();
    tenNV=txt_hoTen.getText();
    if(tenNV.isEmpty()){
        JOptionPane.showMessageDialog(this, "Tên NV trống");
        txt_hoTen.requestFocus();
        return null; 
    }
    tenDangNhap=txt_tenDangNhap.getText();
    if(tenDangNhap.isEmpty()){
        JOptionPane.showMessageDialog(this, "Tên đăng nhập trống");
        txt_tenDangNhap.requestFocus();
        return null; 
    }
        try {
            Check_Email.parseEmail(txt_tenDangNhap.getText());
        } catch (Exception ex) {
            thongbao+="Tên đăng nhập không hợp lệ!(Phải là email)";
        }
        if (thongbao!="") {
            JOptionPane.showMessageDialog(null, thongbao);
            return null;
        }
        
    matKhau=txt_matKhau.getText();
    if(matKhau.isEmpty()){
        JOptionPane.showMessageDialog(this, "Mật khẩu trống");
        txt_matKhau.requestFocus();
        return null; 
    }
    else{
    if (rdo_quanLy.isSelected()) {
            phanQuyen = true;
        } else {
            phanQuyen = false;
        }
    if (rdo_hoatDong.isSelected()) {
            trangThai = true;
        } else {
            trangThai = false;
        }
    Model_ThietLap tl = new Model_ThietLap(maNV, tenNV, tenDangNhap, matKhau, phanQuyen, trangThai);
        if(rp.CheckTenDangNhap(tenDangNhap.trim())){
        JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại");
        return null;
    }
//        if(rp.CheckMaNV(maNV.trim())){
//        JOptionPane.showMessageDialog(null, "Mã nhân viên đã tồn tại!");
//        return null;
//    }

        return tl;
    }

    }
    Model_ThietLap readForm1(){
    String maNV;
    String tenNV;
    String tenDangNhap;
    String matKhau;
    boolean phanQuyen;
    boolean trangThai;
    
    maNV=txt_maNV.getText();
    tenNV=txt_hoTen.getText();
    if(tenNV.isEmpty()){
        JOptionPane.showMessageDialog(this, "Tên NV trống");
        txt_hoTen.requestFocus();
        return null; 
    }
    tenDangNhap=txt_tenDangNhap.getText();
    if(tenDangNhap.isEmpty()){
        JOptionPane.showMessageDialog(this, "Tên đăng nhập trống");
        txt_tenDangNhap.requestFocus();
        return null; 
    }
    matKhau=txt_matKhau.getText();
    if(matKhau.isEmpty()){
        JOptionPane.showMessageDialog(this, "Mật khẩu trống");
        txt_matKhau.requestFocus();
        return null; 
    }
    else{
    if (rdo_quanLy.isSelected()) {
            phanQuyen = true;
        } else {
            phanQuyen = false;
        }
    if (rdo_hoatDong.isSelected()) {
            trangThai = true;
        } else {
            trangThai = false;
        }
    Model_ThietLap tl = new Model_ThietLap(maNV, tenNV, tenDangNhap, matKhau, phanQuyen, trangThai);
//        if(rp.CheckTenDangNhap(tenDangNhap.trim())){
//        JOptionPane.showMessageDialog(null, "Tên đăng nhập đã tồn tại!");
//        return null;
//    }
//        if(rp.CheckMaNV(maNV.trim())){
//        JOptionPane.showMessageDialog(null, "Mã nhân viên đã tồn tại!");
//        return null;
//    }
        return tl;
    }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdo_hoatDong;
    private javax.swing.JRadioButton rdo_ngungHoatDong;
    private javax.swing.JRadioButton rdo_nhanVien;
    private javax.swing.JRadioButton rdo_quanLy;
    private javax.swing.JTable tbl_taiKhoan;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_hoTen;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JTextField txt_tenDangNhap;
    // End of variables declaration//GEN-END:variables
}
