/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Product.form1;

import Model_Voucher.Model_LichSuHoaDon;
import Model_Voucher.Model_ChiTietHoaDon;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Repository.Repository_LichSuHoaDon;
import Repository.Repository_ChiTietHoaDon;
/**
 *
 * @author ADMIN
 */
public class Form_LichSu extends javax.swing.JPanel {
    private Repository_LichSuHoaDon rp = new Repository_LichSuHoaDon();
    private Repository_ChiTietHoaDon rpcthd = new Repository_ChiTietHoaDon();
    private DefaultTableModel mol = new DefaultTableModel();
    private DefaultTableModel molcthd = new DefaultTableModel();
    private ArrayList<Model_LichSuHoaDon>  list = new ArrayList<>();
    private ArrayList<Model_ChiTietHoaDon>  listcthd = new ArrayList<>();
    private int i = -1;   
    /**
     * Creates new form Form_LichSu
     */
    public Form_LichSu() {
        initComponents();
        mol = (DefaultTableModel) tbl_lichSuHoaDon.getModel();
        molcthd = (DefaultTableModel) tbl_ChiTietHoaDon.getModel();
        list = rp.getAll();
        
        showDataTable1(list);
        showDataTable2(listcthd);
    }
    public void showDataTable1(ArrayList<Model_LichSuHoaDon> ls){
        mol.setRowCount(0);
        for (Model_LichSuHoaDon model_LichSuHoaDon : ls) {
            mol.addRow(new Object[]{
                model_LichSuHoaDon.getId(),model_LichSuHoaDon.getMaHD(),model_LichSuHoaDon.getTenNV(),model_LichSuHoaDon.getTenKH(),
                model_LichSuHoaDon.getTongTien(),model_LichSuHoaDon.getNgayTao(),model_LichSuHoaDon.isTrangThai()?"Đã thanh toán":"Chưa thanh toán"
            });
        }
    }
    public void showDataTable2(ArrayList<Model_ChiTietHoaDon> al){
        molcthd.setRowCount(0);
        for (Model_ChiTietHoaDon model_ChiTietHoaDon : al) {
            molcthd.addRow(new Object[]{
                model_ChiTietHoaDon.getId(),model_ChiTietHoaDon.getMaSP(),model_ChiTietHoaDon.getTenSP(),
                model_ChiTietHoaDon.getSoLuong(),model_ChiTietHoaDon.getDonGia(),model_ChiTietHoaDon.getTongTien(),               
                model_ChiTietHoaDon.isTrangThai()?"Đã thanh toán":"Chưa thanh toán"
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_ChiTietHoaDon = new View.swing.Table();
        btn_TimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_lichSuHoaDon = new View.swing.Table();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("LỊCH SỬ");

        tbl_ChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã SP", "Tên SP", "Số Lượng", "Đơn Giá", "Tổng Tiền", "Trạng Thái"
            }
        ));
        tbl_ChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_ChiTietHoaDon);

        btn_TimKiem.setBackground(new java.awt.Color(102, 102, 255));
        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Timkiem.png"))); // NOI18N
        btn_TimKiem.setText("TÌM KIẾM");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        tbl_lichSuHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã HĐ", "Tên NV", "Tên KH", "Tổng Tiền", "Ngày Tạo", "Trạng Thái"
            }
        ));
        tbl_lichSuHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lichSuHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_lichSuHoaDon);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(127, 127, 127));
        jLabel9.setText("Lịch Sử Hóa Đơn");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(127, 127, 127));
        jLabel10.setText("Thông Tin Sản Phẩm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_TimKiem)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(443, 443, 443)
                        .addComponent(jLabel1)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btn_TimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        String ma=JOptionPane.showInputDialog(this, "Mời nhập mã cần tìm?");
        if(rp.TimMa(ma).isEmpty()){
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
        }
        else{
            JOptionPane.showMessageDialog(this, "Có  tìm thấy");
            this.showDataTable1(rp.TimMa(ma));
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void tbl_ChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ChiTietHoaDonMouseClicked
   
    }//GEN-LAST:event_tbl_ChiTietHoaDonMouseClicked

    private void tbl_lichSuHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lichSuHoaDonMouseClicked
        int selectedRow = tbl_lichSuHoaDon.getSelectedRow();
        if (selectedRow != -1) {
            int ma_hoa_don = Integer.parseInt(tbl_lichSuHoaDon.getValueAt(selectedRow, 0).toString());
            showDataTable2(rpcthd.getAll(ma_hoa_don));
        }   
            // TODO add your handling code here:
    }//GEN-LAST:event_tbl_lichSuHoaDonMouseClicked




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private View.swing.Table tbl_ChiTietHoaDon;
    private View.swing.Table tbl_lichSuHoaDon;
    // End of variables declaration//GEN-END:variables
}
