/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Product.form1;

import Repository.Repository_NhaCC;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class Form_NCC extends javax.swing.JPanel {
    ArrayList<Model.Model_NhaCC> lst;
    Repository_NhaCC repo;
    private Component rootPane;
    
    /**
     * Creates new form Form_NCC
     */
    public Form_NCC() throws SQLException {
        initComponents();
        lst = new ArrayList();
        repo = new Repository_NhaCC();
        getdata();
        loaddata();
    }
    
    public void getdata() throws SQLException {
        lst = repo.getdata();
    }
   
    public void loaddata() {
        String[] header = {"Mã Nhà CC", "Tên Nhà CC ","Địa Chỉ ","Số điện thoại ","Trạng thái "};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        tbl_NhaCC.setModel(model);
        
        for (Model.Model_NhaCC ncc : lst) {      
            Object[] row = {ncc.getMaNCC(),ncc.getTenNCC(),ncc.getDiaChi(),ncc.getSoDienThoai(),ncc.isTrangThai()?"Đối tác ":"Nhà cung cấp sỉ lẻ "};
            model.addRow(row); 
        }
    }
    
    public boolean checkMa(String ma){
        
        for (Model.Model_NhaCC ncc : lst) {
            if(ncc.getMaNCC().equals(ma)){
                return true;
            }                
        }
       return false;
    }
    
    public boolean checkTen(String ten){
        
        for (Model.Model_NhaCC ncc : lst) {
            if(ncc.getTenNCC().equals(ten)){
                return true;
            }                
        }
       return false;
    }
    
    
    
    public boolean checkSDT(String sdt){
        
        for (Model.Model_NhaCC ncc : lst) {
            if(ncc.getSoDienThoai().equals(sdt)){
                
                return true;
            }                
        }
       return false;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NhaCC = new View.swing.Table();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_TimKiem = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txt_MaNCC = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("NHÀ CUNG CẤP");

        txt_HoTen.setBackground(new java.awt.Color(127, 127, 127));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("Tên Nhà CC:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("SĐT: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(127, 127, 127));
        jLabel5.setText("Mã NCC:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(127, 127, 127));
        jLabel17.setText("ĐỊA CHỈ:");

        txt_SDT.setBackground(new java.awt.Color(127, 127, 127));

        tbl_NhaCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhà CC", "Tên Nhà CC", "SĐT", "Email", "Địa Chỉ", "Trạng Thái ", "Ghi Chú"
            }
        ));
        tbl_NhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhaCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NhaCC);

        btn_Them.setBackground(new java.awt.Color(102, 102, 255));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N
        btn_Them.setText("THÊM");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(102, 102, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/SAVE.png"))); // NOI18N
        btn_Sua.setText("SỬA");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_TimKiem.setBackground(new java.awt.Color(102, 102, 255));
        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Timkiem.png"))); // NOI18N
        btn_TimKiem.setText("TÌM KIẾM");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Reset.setBackground(new java.awt.Color(102, 102, 255));
        btn_Reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/RESET.png"))); // NOI18N
        btn_Reset.setText("LÀM MỚI");
        btn_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ResetActionPerformed(evt);
            }
        });

        txt_DiaChi.setBackground(new java.awt.Color(127, 127, 127));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(127, 127, 127));
        jLabel8.setText("Tìm Mã NCC:");

        txt_TimKiem.setBackground(new java.awt.Color(127, 127, 127));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(127, 127, 127));
        jLabel23.setText("Trạng thái :");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton1.setText("Đối tác");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jRadioButton2.setText("Nhà cung cấp sỉ lẻ ");

        txt_MaNCC.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txt_MaNCC.setText(".");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_Them)
                                .addGap(55, 55, 55)
                                .addComponent(btn_Sua)
                                .addGap(58, 58, 58)
                                .addComponent(btn_Reset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel17)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(291, 291, 291)
                                                .addComponent(jLabel23)))
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton1))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btn_TimKiem))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(32, 32, 32))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel23)
                    .addComponent(jRadioButton1)
                    .addComponent(txt_MaNCC))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButton2))
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimKiem)
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Reset))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
         String tenNhaCC = txt_TimKiem.getText().toUpperCase();
        
    try {
        if(repo.timKiem(tenNhaCC).isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy mã Nhà cung cấp ");
            getdata();
            loaddata();
        }
        else{
            lst = repo.timKiem(tenNhaCC);
            loaddata();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Form_KhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void tbl_NhaCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NhaCCMouseClicked
        int selectedRow = tbl_NhaCC.getSelectedRow();        
        
        if(selectedRow >= 0){
           Model.Model_NhaCC ncc = lst.get(selectedRow);
           txt_MaNCC.setText(ncc.getMaNCC());
           txt_HoTen.setText(ncc.getTenNCC());
           txt_SDT.setText(ncc.getSoDienThoai());
           txt_DiaChi.setText(ncc.getDiaChi());
           if (ncc.isTrangThai()) {
                buttonGroup1.setSelected(jRadioButton1.getModel(), true);
                buttonGroup1.setSelected(jRadioButton2.getModel(), false);
            } else {
                buttonGroup1.setSelected(jRadioButton1.getModel(), false);
                buttonGroup1.setSelected(jRadioButton2.getModel(), true);
            }
        }
        tbl_NhaCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NhaCCMouseClicked(evt);
            }
        }
        );
    }//GEN-LAST:event_tbl_NhaCCMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        
        boolean check = true;
        Model.Model_NhaCC ncc = new Model.Model_NhaCC();
        if(checkMa(txt_MaNCC.getText())){
            JOptionPane.showMessageDialog(rootPane, "Mã nhà cung cấp đã tồn tại ");
            check = false;
        }
        else if(txt_HoTen.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Tên nhà cung cấp không được để trống");
                txt_HoTen.requestFocus();
                check = false;
        } else if (checkTen(txt_HoTen.getText())){
                JOptionPane.showMessageDialog(rootPane, "Tên nhà cung cấp đã tồn tại ");
                txt_HoTen.requestFocus();
                check = false;
        }
        
        else if(txt_DiaChi.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Địa chỉ không được để trống");
                txt_DiaChi.requestFocus();
                check = false;
            }
        
        else if(txt_SDT.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại không được để trống");
                txt_SDT.requestFocus();
                check = false;
            }else if(checkSDT(txt_SDT.getText())){
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại đã tồn tại !!");
                txt_SDT.requestFocus();
                check = false;
            }
        
        if(check == true){
            
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?");
            if(chon == 0){
            ncc.setTenNCC(txt_HoTen.getText());
            ncc.setDiaChi(txt_DiaChi.getText());
            ncc.setSoDienThoai(txt_SDT.getText());
            ncc.setTrangThai(jRadioButton1.isSelected());
             try {
                repo.insert(ncc);
                getdata();
                loaddata();
                JOptionPane.showMessageDialog(rootPane, "Đã thêm nhà cung cấp mới thành công");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Đã thêm nhà cung cấp mới thất bại");
                Logger.getLogger(Form_KhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
            }
             
            }else{
                JOptionPane.showMessageDialog(this, "Không thêm!");
            }
            
        }
        
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
          int index = tbl_NhaCC.getSelectedRow();
          boolean check = true ;
          if(txt_HoTen.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Tên nhà cung cấp không được để trống");
                txt_HoTen.requestFocus();
                check = false;
        } else if (checkTen(txt_HoTen.getText())){
                JOptionPane.showMessageDialog(rootPane, "Tên nhà cung cấp đã tồn tại ");
                txt_HoTen.requestFocus();
                check = false;
        }
        
        if(txt_DiaChi.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Địa chỉ không được để trống");
                txt_DiaChi.requestFocus();
                check = false;
            }
        
        if(txt_SDT.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Số điện thoại không được để trống");
                txt_SDT.requestFocus();
                check = false;
            }
//        else 
//            if(checkSDT(txt_SDT.getText())){
//                JOptionPane.showMessageDialog(rootPane, "Số điện thoại đã tồn tại !!");
//                txt_SDT.requestFocus();
//                check = false;
//            }
              
                 
            if(index == -1){
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn dòng để cập nhật");
            }else if (check == true){
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thay đổi không?");
            if(chon == 0){
                Model.Model_NhaCC ncc = lst.get(index);    
            ncc.setTenNCC(txt_HoTen.getText());
            ncc.setDiaChi(txt_DiaChi.getText());
            ncc.setSoDienThoai(txt_SDT.getText());
            ncc.setTrangThai(jRadioButton1.isSelected());
           try {
                int result = repo.update(ncc);
                if (result > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật nhà cung cấp thành công");
                    getdata();
                    loaddata();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật nhà cung cấp thất bại");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Form_KhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
                JOptionPane.showMessageDialog(this, "Không cập nhập thông tin!");
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ResetActionPerformed
           txt_MaNCC.setText("");
           txt_HoTen.setText("");
           txt_SDT.setText("");
           txt_DiaChi.setText("");
           jRadioButton1.setSelected(true);
           loaddata();
    }//GEN-LAST:event_btn_ResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private View.swing.Table tbl_NhaCC;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JLabel txt_MaNCC;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TimKiem;
    // End of variables declaration//GEN-END:variables
}
