/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.Product.form1;

import Repository.Repository_KhuyenMai;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;



/**
 *
 * @author ADMIN
 */
public class Form_KhuyenMai extends javax.swing.JPanel {
ArrayList<Model.Model_KhuyenMai> lst;
     Repository_KhuyenMai repo;
    private Component rootPane;
    /**
     * Creates new form Form_KhuyenMai
     */
    public Form_KhuyenMai() throws SQLException {
        initComponents();
        lst = new ArrayList();
        repo = new Repository_KhuyenMai();
        getdata();
        loaddata();
        
    }
    
   public void getdata() throws SQLException {
        lst = repo.getdata();
        Date dateNow = new Date();
        ngayBatDau.setDate(dateNow);
        ngayKetThuc.setDate(dateNow);
    }
   
    public void loaddata() {
        String[] header = {"Mã voucher","Tên","Mức giảm","Điều kiện ","Số lần","Ngày bắt đầu","Ngày kết thúc","Trạng thái", "Ngày tạo","Ngày cập nhật"};
        DefaultTableModel model = new DefaultTableModel(header, 0);
        tbl_DanhSachKM.setModel(model);
        Date dateNow = new Date();
        int trangThai = 0;
        
        for (Model.Model_KhuyenMai km : lst) {
            if(km.getNgay_bat_dau().after(dateNow) && km.getNgay_het_han().before(dateNow)){
                trangThai = 1;
            }
            Object[] row = {km.getMa_voucher(),km.getTen_giam_gia(), Math.round(km.getPhan_tram_giam_gia()) + "%",
                String.format("%,.3f VNĐ ", km.getDieu_kien_ap_dung()),
                km.getSo_lan_su_dung(),
                km.getNgay_bat_dau(),
                km.getNgay_het_han(),
                trangThai == 0?"Hết Hạn":"Đang áp dụng ",
                km.getNgay_tao(),
                km.getNgay_cap_nhat()};
            model.addRow(row);
            
        }
        
        
    }
    
    public boolean checkMa(String ma){
        
        for (Model.Model_KhuyenMai km : lst) {
            if(km.getMa_voucher().equals(ma)){
                return true;
            }                
        }
       return false;
    }
    
    public boolean checkTen(String ten){
        
        for (Model.Model_KhuyenMai km : lst) {
            if(km.getTen_giam_gia().equals(ten)){
                return true;
            }                
        }
       return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_TenVoucher = new javax.swing.JTextField();
        txt_Solan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_DieuKien = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_MoTa = new javax.swing.JTextArea();
        txt_mucGiam1 = new javax.swing.JTextField();
        txt_MaVoucher = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        paneBorder1 = new View.swing.PaneBorder();
        btn_Sua = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        ngayKetThuc = new com.toedter.calendar.JDateChooser();
        ngayBatDau = new com.toedter.calendar.JDateChooser();
        txt_TimKiem = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btn_TimKiem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_DanhSachKM = new View.swing.Table();
        jLabel14 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("KHUYỄN MÃI");

        jPanel1.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(127, 127, 127));
        jLabel4.setText("CHƯƠNG TRÌNH KHUYỄN MÃI");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(127, 127, 127));
        jLabel5.setText("Mã voucher:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(127, 127, 127));
        jLabel6.setText("Tên giảm giá: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(127, 127, 127));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(127, 127, 127));
        jLabel8.setText("Điều kiện áp dụng :");

        txt_TenVoucher.setBackground(new java.awt.Color(130, 130, 130));
        txt_TenVoucher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TenVoucher.setForeground(new java.awt.Color(255, 255, 255));
        txt_TenVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenVoucherActionPerformed(evt);
            }
        });

        txt_Solan.setBackground(new java.awt.Color(130, 130, 130));
        txt_Solan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Solan.setForeground(new java.awt.Color(255, 255, 255));
        txt_Solan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SolanActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(127, 127, 127));
        jLabel13.setText("Mức giảm:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(127, 127, 127));
        jLabel15.setText("Số lần sử dụng :");

        txt_DieuKien.setBackground(new java.awt.Color(130, 130, 130));
        txt_DieuKien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_DieuKien.setForeground(new java.awt.Color(255, 255, 255));
        txt_DieuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DieuKienActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(127, 127, 127));
        jLabel12.setText("Mô tả :");

        txt_MoTa.setBackground(new java.awt.Color(127, 127, 127));
        txt_MoTa.setColumns(20);
        txt_MoTa.setForeground(new java.awt.Color(255, 255, 255));
        txt_MoTa.setRows(5);
        jScrollPane2.setViewportView(txt_MoTa);

        txt_mucGiam1.setBackground(new java.awt.Color(130, 130, 130));
        txt_mucGiam1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_mucGiam1.setForeground(new java.awt.Color(255, 255, 255));
        txt_mucGiam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mucGiam1ActionPerformed(evt);
            }
        });

        txt_MaVoucher.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txt_MaVoucher.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_MaVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(txt_DieuKien, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Solan, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txt_mucGiam1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_MaVoucher))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TenVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_mucGiam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_DieuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Solan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(127, 127, 127));
        jLabel9.setText("Thời gian sử dụng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(127, 127, 127));
        jLabel10.setText("Từ ngày: ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(127, 127, 127));
        jLabel11.setText("Đến ngày:");

        paneBorder1.setBackground(new java.awt.Color(204, 204, 204));

        btn_Sua.setBackground(new java.awt.Color(102, 102, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(255, 255, 255));
        btn_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/SAVE.png"))); // NOI18N
        btn_Sua.setText("SỬA");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_LamMoi.setBackground(new java.awt.Color(102, 102, 255));
        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/RESET.png"))); // NOI18N
        btn_LamMoi.setText("LÀM MỚI");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        btn_Them.setBackground(new java.awt.Color(102, 102, 255));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(255, 255, 255));
        btn_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/ADD.png"))); // NOI18N
        btn_Them.setText("THÊM");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneBorder1Layout = new javax.swing.GroupLayout(paneBorder1);
        paneBorder1.setLayout(paneBorder1Layout);
        paneBorder1Layout.setHorizontalGroup(
            paneBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_Them)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btn_LamMoi)
                .addGap(69, 69, 69))
        );
        paneBorder1Layout.setVerticalGroup(
            paneBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBorder1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(paneBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_Them))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        ngayKetThuc.setDateFormatString("yyyy-MM-dd");

        ngayBatDau.setDateFormatString("yyyy-MM-dd");

        txt_TimKiem.setBackground(new java.awt.Color(130, 130, 130));
        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        txt_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TimKiemActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(127, 127, 127));
        jLabel16.setText("Tìm kiếm mã voucher :");

        btn_TimKiem.setBackground(new java.awt.Color(102, 102, 255));
        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/Timkiem.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paneBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_TimKiem))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(ngayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(64, 64, 64)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ngayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TimKiem)
                .addGap(87, 87, 87)
                .addComponent(paneBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(ngayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(312, Short.MAX_VALUE)))
        );

        tbl_DanhSachKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã voucher", "Tên voucher", "Mức giảm", "Điều kiện áp dụng", "Số lần sử dụng", "Ngày bắt đầu ", "Ngày kết thúc", "Trang thái", "Mô tả", "Ngày tạo", "Ngày cập nhật"
            }
        ));
        tbl_DanhSachKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhSachKMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_DanhSachKM);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(127, 127, 127));
        jLabel14.setText("Danh Sách Khuyến Mãi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1039, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenVoucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenVoucherActionPerformed

    private void txt_SolanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SolanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SolanActionPerformed

    private void txt_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TimKiemActionPerformed

    private void txt_DieuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DieuKienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DieuKienActionPerformed

    private void tbl_DanhSachKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_DanhSachKMMouseClicked
        int selectedRow = tbl_DanhSachKM.getSelectedRow();
        if(selectedRow >= 0){
           Model.Model_KhuyenMai km = lst.get(selectedRow);
           
           
           txt_MaVoucher.setText(km.getMa_voucher());
           txt_TenVoucher.setText(km.getTen_giam_gia());
           txt_mucGiam1.setText(String.format("%.0f ",km.getPhan_tram_giam_gia())+"%");
           txt_DieuKien.setText(String.format("%,.3f VNĐ", km.getDieu_kien_ap_dung()));
           txt_Solan.setText(Integer.toString(km.getSo_lan_su_dung()));
           ngayBatDau.setDate(km.getNgay_bat_dau());
           ngayKetThuc.setDate(km.getNgay_het_han());
           txt_MoTa.setText(km.getMo_ta());
           
        }
        tbl_DanhSachKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_DanhSachKMMouseClicked(evt);
            }
        }
        );
    }//GEN-LAST:event_tbl_DanhSachKMMouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
            boolean check = true ;
            Model.Model_KhuyenMai km = new Model.Model_KhuyenMai();
            
            String dateBD =  new SimpleDateFormat("yyyy-MM-dd").format(ngayBatDau.getDate());
            java.sql.Date dateBD2 = java.sql.Date.valueOf(dateBD);
                  
                      
            String dateKT =  new SimpleDateFormat("yyyy-MM-dd").format(ngayKetThuc.getDate());
            java.sql.Date dateKT2 = java.sql.Date.valueOf(dateKT);
            
            Date dateNow = new Date();
                       
            
            String maVoucher = txt_MaVoucher.getText();
            String tenVoucher = txt_TenVoucher.getText();
            double mucGiam = Double.parseDouble(txt_mucGiam1.getText());
            double dieuKien = Double.parseDouble(txt_DieuKien.getText());
            int soLan = Integer.parseInt(txt_Solan.getText());
            
            if(checkMa(txt_MaVoucher.getText())){
                JOptionPane.showMessageDialog(rootPane, "Mã Giảm Giá đã tồn tại");
            }
            else if(tenVoucher.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Tên Giảm giá không được để trống");
                txt_TenVoucher.requestFocus();
                check = false;
            }else if (checkTen(tenVoucher)){
                JOptionPane.showMessageDialog(rootPane, "Tên Giảm giá đã tồn tại !!");
                txt_TenVoucher.requestFocus();
                check = false;
            }
            
            else if(txt_mucGiam1.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Mức giảm giá không được để trống");
                txt_mucGiam1.requestFocus();
                check = false;
            }else if (!isDouble(txt_mucGiam1.getText())){
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu nhập vào ở mức giảm phải là kiểu số ");
                txt_mucGiam1.requestFocus();
                check = false;
            }
            else if (mucGiam < 0 || mucGiam > 100){
                JOptionPane.showMessageDialog(rootPane, "Mức giảm nằm trong khoảng từ 0 đến 100");
                txt_mucGiam1.requestFocus();
                check = false;
            }
            else if (txt_DieuKien.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Điều kiện giảm không được để trống");
                txt_DieuKien.requestFocus();
                check = false;
            }
            else if(!isDouble(txt_DieuKien.getText().trim())){
                
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu nhập vào ở ô điều kiện phải là kiểu số ");
                txt_mucGiam1.requestFocus();
                check = false;
            }           
            else if(ngayBatDau.getDate() == null ){
                JOptionPane.showMessageDialog(rootPane, "Ngày bắt đầu không được để trống");
                ngayBatDau.requestFocus();
                check = false;
            }else if(ngayBatDau.getDate().before(dateNow)){
                JOptionPane.showMessageDialog(rootPane, "Không thể tạo ngày bắt đầu trước ngày hôm nay");
                ngayBatDau.requestFocus();
                check = false;
            }
            else if(ngayKetThuc.getDate() == null){
                JOptionPane.showMessageDialog(rootPane, "Ngày kết thúc không được để trống");
                ngayKetThuc.requestFocus();
                check = false;
            }else if(ngayKetThuc.getDate().before(ngayBatDau.getDate())){
                JOptionPane.showMessageDialog(rootPane, "Không thể tạo ngày kết thúc trước ngày bắt đầu ");
                ngayKetThuc.requestFocus();
                check = false;
            }
            if(check == true){ 
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không?");
            if(chon == 0){
            km.setMa_voucher(maVoucher);
            km.setTen_giam_gia(tenVoucher);
            km.setPhan_tram_giam_gia(mucGiam);
            km.setDieu_kien_ap_dung(dieuKien);
            km.setNgay_bat_dau(dateBD2);
            km.setNgay_het_han(dateKT2);
            km.setSo_lan_su_dung(soLan);
            km.setMo_ta(txt_MoTa.getText());
            try {
                repo.insert(km);
                getdata();
                loaddata();
                JOptionPane.showMessageDialog(rootPane, "Đã thêm Giảm giá thành công");
            } catch (SQLException ex) {
                Logger.getLogger(Form_KhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
            }
            } else{
                 JOptionPane.showMessageDialog(this, "Không thêm!");
            }          
            }  
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
           
           Date today = new Date();        
           txt_MaVoucher.setText("");
           txt_TenVoucher.setText("");
           txt_mucGiam1.setText("");
           txt_DieuKien.setText("");
           txt_Solan.setText("");
           ngayBatDau.setDate(today);
           ngayKetThuc.setDate(today);
           txt_MoTa.setText("");
           loaddata();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        int index = tbl_DanhSachKM.getSelectedRow();
        boolean check = true ;
        if(index == -1){
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn dòng để cập nhật");
        }else{
            Model.Model_KhuyenMai km = lst.get(index);    
            
              
            String dateBD =  new SimpleDateFormat("yyyy-MM-dd").format(ngayBatDau.getDate());
            java.sql.Date dateBD2 = java.sql.Date.valueOf(dateBD);
                  
                      
            String dateKT =  new SimpleDateFormat("yyyy-MM-dd").format(ngayKetThuc.getDate());
            java.sql.Date dateKT2 = java.sql.Date.valueOf(dateKT);
            
            Date dateNow = new Date();
            
            
            String maVoucher = txt_MaVoucher.getText();
            String tenVoucher = txt_TenVoucher.getText();
            double mucGiam = Double.parseDouble(txt_mucGiam1.getText());
            double dieuKien = Double.parseDouble(txt_DieuKien.getText());
            int soLan = Integer.parseInt(txt_Solan.getText());
                      
            
            if(tenVoucher.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Tên Giảm giá không được để trống");
                txt_TenVoucher.requestFocus();
                check = false;
            }else if (checkTen(tenVoucher)){
                JOptionPane.showMessageDialog(rootPane, "Tên Giảm giá đã tồn tại !!");
                txt_TenVoucher.requestFocus();
                check = false;
            }
            
            else if(txt_mucGiam1.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Mức giảm giá không được để trống");
                txt_mucGiam1.requestFocus();
                check = false;
            }else if (mucGiam < 0 || mucGiam > 100){
                JOptionPane.showMessageDialog(rootPane, "Mức giảm nằm trong khoảng từ 0 đến 100");
                txt_mucGiam1.requestFocus();
                check = false;
            }
            
            else if(ngayBatDau.getDate() == null){
                JOptionPane.showMessageDialog(rootPane, "Ngày bắt đầu không được để trống");
                ngayBatDau.requestFocus();
                check = false;
            }
            else if(ngayKetThuc.getDate() == null){
                JOptionPane.showMessageDialog(rootPane, "Ngày kết thúc không được để trống");
                ngayKetThuc.requestFocus();
                check = false;
            }else if(ngayKetThuc.getDate().before(ngayBatDau.getDate())){
                JOptionPane.showMessageDialog(rootPane, "Không thể tạo ngày kết thúc trước ngày bắt đầu ");
                ngayKetThuc.requestFocus();
                check = false;
            }
            
            if(check == true){  
            int chon = JOptionPane.showConfirmDialog(this, "Bạn có muốn cập nhật thông tin mới không?"); 
            if(chon == 0){ 
            km.setMa_voucher(maVoucher);
            km.setTen_giam_gia(tenVoucher);
            km.setPhan_tram_giam_gia(mucGiam);
            km.setDieu_kien_ap_dung(dieuKien);
            km.setNgay_bat_dau(dateBD2);
            km.setNgay_het_han(dateKT2);
            km.setSo_lan_su_dung(soLan);
            km.setMo_ta(txt_MoTa.getText());           
           try {
                int result = repo.update(km);
                if (result > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật thông tin mới  thành công");
                    getdata();
                    loaddata();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Cập nhật điểm thất bại");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Form_KhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            }else{
                JOptionPane.showMessageDialog(this, "Không cập nhập thêm !");
            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void txt_mucGiam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mucGiam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mucGiam1ActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
       
   String tenVoucher = txt_TimKiem.getText().toUpperCase();
        
        try {
        if(repo.timKiem(tenVoucher).isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy mã voucher ");
            getdata();
            loaddata();
        }
        else{
            lst = repo.timKiem(tenVoucher);
            loaddata();
        }
    } catch (SQLException ex) {
        Logger.getLogger(Form_KhuyenMai.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btn_TimKiemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser ngayBatDau;
    private com.toedter.calendar.JDateChooser ngayKetThuc;
    private View.swing.PaneBorder paneBorder1;
    private View.swing.Table tbl_DanhSachKM;
    private javax.swing.JTextField txt_DieuKien;
    private javax.swing.JLabel txt_MaVoucher;
    private javax.swing.JTextArea txt_MoTa;
    private javax.swing.JTextField txt_Solan;
    private javax.swing.JTextField txt_TenVoucher;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_mucGiam1;
    // End of variables declaration//GEN-END:variables
private static boolean isDouble(String input) {
    try {
        Double.parseDouble(input);
        return true;
    } catch (NumberFormatException e) {
        return false; // Trả về false nếu không phải double
    }
}
}
